version: '3'
services:

##########################################################
  redis-on:
    container_name: redis-on
    image: redis
    command: --requirepass "Redis123!@#" 
    ports:
      - "6379:6379"
    networks:
      - greennet

 ##########################################################
  msd-zipcode-v1-api-on:
    container_name: msd-zipcode-v1-api-on
    #image: msd-zipcode-v1-api
    build:
      context: ../MSD.ZipCode.V1
    ports:
      - 8091:80
    networks:
      - greennet

##########################################################
  msd-zipcode-v2-api-on:
    container_name: msd-zipcode-v2-api-on
    #image: msd-zipcode-v2-api
    build:
      context: ../MSD.ZipCode.V2
    ports:
      - 8092:80
    networks:
      - greennet
    depends_on:
      - redis-on

##########################################################
  msd-product-api-on:
    container_name: msd-product-api-on
    #image: msd-product-api
    build:
      context: ../MSD.Product
    ports:
      - 8090:80
    networks:
      - greennet
    depends_on:
      - msd-zipcode-v1-api-on
      - msd-zipcode-v2-api-on

networks:
  greennet:
    driver: bridge